config/routes.rb
Rails.application.routes.draw do
  get 'pledge/show'

  get 'pledge/create' => 'pledge#new', :as => :pledge

  get 'home/index'

  root 'home#index'

  resources :projects do
    resources :rewards do
      resources :pledges
    end
  end

  resources :users
  resources :user_sessions

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  # def initialize(user)

  #   user ||= User.new
  #   if user.owner?
  #     can :read, :create, :update, :destroy, Project
  #    else
  #     can :read, Project
  #     can :create, :update, Pledge
  #   end

end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/pledge.rb
class Pledge < ActiveRecord::Base
	belongs_to :backer, class_name: "User"
	belongs_to :project
	belongs_to :reward

end

app/models/project.rb
class Project < ActiveRecord::Base
	
  mount_uploader :avatar, AvatarUploader

	belongs_to :owner, class_name: 'User'
	has_many :rewards
  has_many :pledges

	validates :owner, presence: true
  validates :name, :description, :funding_goal, :start_date, :end_date, presence: true

  def ensure_data
    if start_date > end_date
      errors.add(:end_date, "Should not end before it starts")
    end

    if start_date >= Time.now
      errors.add(:start_date, "Should not be in the past")
    end

    if end_date >= Time.now
      errors.add(:end_date, "Should not be in the past")
    end  

    if end_date >= Time.now + 2.months
      errors.add(:end_date, "Projects should not last longer than 2 months")
    end  
  end

	accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: :true
	
  def amount_raised
    pledges.sum('amount')
  end

  def send_emails_if_necessary
    return unless funding_goal == amount_raised
    pledges.map(&:backer).each do |backer|
      UserMailer.fully_funded(backer).deliver_now
    end
    UserMailer.fully_funded(owner).deliver_now
  end

  def self.select_categories
    %w[Art Comics Crafts Dance Design Fashion Film\ &\ Video Food Games Journalism Music Photography Publishing Technology Theatre]
  end

end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :project
	has_many :pledges

	validates :title, :description, :amount, presence: true

	def number_of_backers
		pledges.count
	end 
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 8 }
  validates :password, confirmation: true
  validates :first_name, :last_name, :email, :password_confirmation, presence: true
  validates :email, uniqueness: true


  has_many :pledges, foreign_key: :backer_id
  has_many :backed_projects, through: :pledges, source: :project
  has_many :owned_projects, class_name: 'Project', foreign_key: :owner_id

  def total_pledges
    pledges.pluck(:amount).sum(0)
  end

  def money_spent
  	pledges.sum('amount')
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  def not_authenticated
  	redirect_to login_path, alert: "Please login first!"
  end 

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
    @top3projects = Project.where("end_date >  ?", Time.now).order(funding_goal: :DESC).limit(3)

    # order by amount_raised :DESC

    if params[:search]
     		@projects = Project.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    end 

		respond_to do |format|
      	format.html 
      	format.js
  	end 
	end 


end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

	def new
		@pledge = Pledge.new
	end

	def create
		@pledge = Pledge.new
		@pledge.reward_id = params[:reward_id]
		@pledge.project_id = params[:project_id]
		@pledge.amount = params[:amount]
		@pledge.backer = current_user

		if request.xhr?
			if @pledge.save
				@project = @pledge.project
				@project.send_emails_if_necessary
				flash[:notice] = "Congratulations you just pledged!"
				render 'create', layout: false
			else 
				flash.now[:alert] = "Some error occured, retry pledging"
			end
		end

		

	end

	def update
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :require_login, only: [:new, :create, :edit]
	
	def index
		# @project = Project.all
		@project = Project.where("end_date >  ?", Time.now).order('projects.created_at DESC').page(params[:page])
	end

	def new
		@project = Project.new
	end

	def create
		@project = current_user.owned_projects.new(project_params)
		if @project.save
			redirect_to project_url(@project), notice: "Project was created!"
		else
			flash.now[:alert] = "Some error occured, retry submitting the project"
			render :new
		 end
	end

	def show
		@project = Project.find(params[:id])

		if request.xhr?
			render @project
		end

	end

	def edit
  		@project = Project.find(params[:id])
  	end

	def update
		@project = Project.find(params[:id])
		if @project.update_attributes(project_params) 
			redirect_to projects_path(@project)
		else
			flash.now[:alert] = "Some error occured, retry editting the project"
			render :edit
		end

	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to root_url
	end

	private
	def project_params
		params.require(:project)
			  .permit(:name, 
			  		  :description, 
			  		  :funding_goal, 
			  		  :start_date, 
			  		  :end_date, 
							:avatar,
							:avatar_cache, 
					  :category,
			  		  rewards_attributes: [ 
			  		  	:id, 
			  		  	:title, 
			  		  	:description,
			  		  	:amount, 
			  		  	:backer_limit, 
			  		  	:_destroy
			  		  ])
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	def new
		@user = User.new
	end 

	def create
		if @user = login(params[:email], params[:password])
			redirect_back_or_to(:projects, notice: 'Login Successful!')
		else
			flash.now[:alert] = 'Login failed'
			render action: 'new'
		end 
	end 

	def destroy
		logout 
		redirect_to(:projects, notice: 'Logged out!')
	end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end 

	def create
		@user = User.new(user_params)

		if @user.save
			auto_login(@user)
			redirect_to projects_url, notice: 'Signed Up!'
		else
			render 'new'
		end 
	end  

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pledge_helper.rb
module PledgeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="row">
	<h2>What's Popular</h2></br>
	<% @top3projects.each do |project| %>
		<div class="medium-4 columns">
			<%= image_tag project.avatar_url(:large) %>
			<h5><strong><%= link_to project.name, "/projects/#{project.id}" %></strong>
			by <em><%= project.owner.first_name %> <%= project.owner.last_name %></em></h5>
			<p>
			<%= project.description %> </br>
			Goal:  <%= number_to_currency project.funding_goal %></br>
			Pledged: <%= number_to_currency project.amount_raised %></br>
			Days to go: <%= (project.end_date - project.start_date).to_i %> days</br>
			</p>
		</div>
	<% end %>
</div>

<div class="row">
	<h3>Find a Project</h3>
	<!-- <h4>Categories</h4>
	<%= Project.select_categories.join(" ") %></br></br>
	-->
	<%= form_tag projects_path, method: :get, remote: true, authentication: false, id: 'search-form' do %>
		<div class="row collapse">
			<div class="small-10 columns">
				<%= text_field_tag :search, params[:search],  placeholder: '' %>
			</div>
			<div class="small-2 columns">
				<%= submit_tag "Search", :class => "button postfix" %>
			</div>
		</br></br>
		</div>
	<% end %>
</div>


<div class="row">
	<div id="projects" data-equalizer>
		<%= render @projects if @projects %>
	</div>
</div>

app/views/home/index.js.erb
$('#projects').html("<%= j(render @projects) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Crowdfunder" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name">
				<h1><a href="<%= root_path %>">CROWDFUNDER</a></h1>
			</li>
			<li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
		</ul>
		<section class="top-bar-section">
			<ul class="left">
      			<li><%= link_to 'Start', new_project_path %></li>
      			<li><%= link_to 'Discover', projects_path %> </li>
      		</ul>
      		<ul class="right">
      			<% if current_user %>
      				<li><a href="#">Signed in as <%= current_user.first_name.capitalize %></a></li>
      				<li><%= link_to 'Profile', user_path(current_user.id) %></li>
   			 		<li><%= link_to 'Logout', :logout, method: :post %></li>
   			 	<% else %>
					<li><%= link_to 'Sign Up', new_user_path %></li>
					<li><%= link_to 'Login', :login %></li>
				<% end %>
   			 </ul>
		</section>
	</nav>
	<div class="row">
		<p id="notice"><%= flash[:notice] %></p>
		<p id="alert"><%= flash[:alert] %></p>
	</div>

    <%= yield %>


  </body>
</html>

app/views/pledges/create.html.erb
<%= @project.amount_raised %>

app/views/pledges/show.html.erb
<h1>Pledge#show</h1>
<p>Find me in app/views/pledge/show.html.erb</p>

app/views/projects/_form.html.erb
<%= form_for(@project, html: {multipart: true}) do |f| %>
  <% if @project.errors.any? %>
      <div id="error_explanation">
        <h3>
          Whoops!
          <%= pluralize(@project.errors.count, "error")%>
          prohibited this project from being saved:
        </h3>
        <ul>
          <% @project.errors.full_messages.each do |message|%>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="large-12 columns">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
      <%= f.label :description %>
      <%= f.text_field :description %>
       </div>
    </div>
  <div class="row">
    <div class="large-4 columns">
    <%= f.label :funding_goal, "Funding Goal" %>
    <%= f.number_field :funding_goal %>
    </div>
  <div class="large-4 columns">
    <%= f.label :start_date, "Project Start Date"%>
    <%= f.date_field :start_date %>
  </div>
  <div class="large-4 columns">
    <%= f.label :end_date, "Project End Date"%>
    <%= f.date_field :end_date %>
  </div>
  </div>
  <div class="row">
    <div class="small-6 columns">
      <%= f.label :category %>
      <%= f.select :category, Project.select_categories %>
    </div>
  </div>
  <div class="row">
    <div class="small-6 columns">
      <%= f.label :avatar, "Upload a Project Photo" %>
      <%= f.file_field :avatar  %>
      <%= f.hidden_field :avatar_cache %>
    </div>
    </div>


    <p>Rewards</p>
    <div class="row">
    <div id="rewards">
      <%= f.fields_for :rewards do |reward| %>
      <%= render 'reward_fields', :f => reward %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'Add a Reward', f, :rewards %>
      </div>
    </div>
    <%= f.submit :submit, :class => "button" %>
<% end %>
</div>

app/views/projects/_project.html.erb
<div class= "small-4 columns" data-equalizer-watch>
	<% if project.avatar_url != nil %>
		<%= image_tag project.avatar_url(:large) %></br>
	<% end %>
	<div class="details"=>
	<%= link_to project.name, "/projects/#{project.id}" %> by <%= project.owner.first_name%> <%= project.owner.last_name%></br>
	About This Project: <%= project.description %> </br>
	<% if (project.category != nil) %>
		Category: <%= project.category %> </br>
	<% end %>
	Funding Goal: <%= number_to_currency project.funding_goal %></br>
	Amount Raised: $<span id="amount"><%= project.amount_raised %></span>.00 </br>
	<%= time_ago_in_words(project.end_date)%> to go!</br></br>

	<div class="row">
		<% if current_user && current_user.backed_projects.include?(@project) %>
			<button>You've backed this project!</button>
		<% end %>
	</div>
</div>
</div>

app/views/projects/_reward_fields.html.erb
<div class="row">
	<div class="nested-fields">
		<div class= "medium-6 column">
			<%= f.label :title %>
			<%= f.text_field :title %>
		</div>
		<div class= "medium-6 column">
			<%= f.label :description %>
			<%= f.text_field :description %>
		</div>
		<div class= "medium-6 column">
			<%= f.label :amount %>
			<%= f.text_field :amount %>
		</div>
		<div class= "medium-6 column">
			<%= f.label :backer_limit %>
			<%= f.text_field :backer_limit %>
		</div>
		<%= link_to_remove_association "Remove Reward", f %>
	</div>
</div>

app/views/projects/edit.html.erb
<div class="row">
<h3>Edit Project</h3>

<%= link_to "Back to Project", "/projects/#{@project.id}" %> | <%= link_to "Delete This Project", @project, method: :delete, data: {confirm: "Are you sure?"} %>

<%= render 'form' %> 
</div>

app/views/projects/index.html.erb
<div class="row">
<h2>Find a Project to Back!</h2></br>
</div>
<div class="row">
<% @project.each do |project| %>
<div class="medium-6 columns">
			<%= image_tag project.avatar_url(:large) %>
			<h5><strong><%= project.name %></strong>
			by <em><%= project.owner.first_name %> <%= project.owner.last_name %></em></h5>
			<p>
			<%= project.description %> </br>
			Goal:  <%= number_to_currency project.funding_goal %></br>
			Pledged: <%= number_to_currency project.amount_raised %></br>
			Days to go: <%= (project.end_date - project.start_date).to_i %> days</br>
				<p><%= link_to "Check it out!", "/projects/#{project.id}" %></p>
			</p>
		</div>
<% end %>

<br>
<br>
</div>

app/views/projects/new.html.erb
<div class="row">
	<h1>Create a project</h1>
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="row">
	<h1><%= @project.name %></h1>
	<% if current_user == @project.owner %>
		<%= link_to "Edit this Project", edit_project_path %>
		<% if @project.amount_raised == 0 %>
			| <%= link_to "Delete this Project", @project, data: {confirm: "Are you sure you want to delete this project?"}, :method => :delete %>
		<% end %>
	<% end %>
</div>

<div id="project_info" class=" row clearfix">
	<%= render @project %>
</div>

<div class="row">
</br>
<h3>Rewards</h3>

<p></p>

<% @project.rewards.each do |reward| %>
  <p>PLEDGE <%= number_to_currency reward.amount %></p>
  <p><%= reward.title %> </p>
  <p>What do ya get? <%= reward.description %></p>
  <p><%= reward.number_of_backers %> backers</p>
	
	<% if current_user %>
	 	<button data-pledge-url="<%= project_reward_pledges_path(@project, reward) %>"
			    class= "pledge_button">
					I'M IN! Pledge $ <span><%= reward.amount %></span>!
		</button>
	<% else %>
		<p>You must be logged in to pledge!<p>
	<% end %>

<% end %>
</div>

app/views/user_sessions/new.html.erb
<div class="row">
	<h1>Login!</h1>
	<div class="medium-6 column">
		<%= form_tag user_sessions_path, :method => :post do %>
			<div class="field">
				<%= label_tag :email %>
				<%= text_field_tag :email %>
			</div>
			<div class="field">
				<%= label_tag :password %>
				<%= password_field_tag :password %>
			</div>
			<div class="actions">
				<%= submit_tag "Login", :class => "button" %>	
			</div>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<div class="row">
<h1>Sign Up!</h1>
<div class="medium-6 column center">
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3>
			  Whoops!
			  <%= pluralize(@user.errors.count, "error")%>
			  prohibited you from creating an account:
			</h3>
			<ul>
			  <% @user.errors.full_messages.each do |message|%>
			  <li><%= message %></li>
			  <% end %>
			</ul>
		</div>
    <% end %>
	<div class="field">
		<%= f.label :first_name, "First Name"%>
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :last_name, "Last Name" %>
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirm Password" %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign Me Up!", :class => "button"%>
	</div>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <h3>Hi <%= current_user.first_name%>, </br>Check out your current project statuses below!</h3></br>

<% current_user.owned_projects.each do |project| %>
<div class="medium-4 columns">
  <h4><%= project.name %></h4>
  <p>
  Project Funding Goal: <%= number_to_currency project.funding_goal %></br>
  Amount Raised to Date: <%= number_to_currency project.pledges.pluck(:amount).sum(0) %></br>
  Current Number of Backers: <%= project.pledges.count %></br>
  Time Remaining to Pledge: <%= distance_of_time_in_words(Time.now, project.end_date) %></br>
  </p>
</div>
  <% end %>


<h3>Projects you've backed:</h3>
 <p>(Total pledged for all projects: <%= number_to_currency current_user.total_pledges %>)</p>
<% current_user.backed_projects.uniq.each do |project| %>
  <div class="medium-4 columns">
    <h4><%= project.name %></h4>
    <p><%= project.description %>
    by <%= project.owner.first_name %> <%= project.owner.last_name %> </br>
    Funding Goal: <%= number_to_currency project.funding_goal %></br>
    Pledged Amount: <%=  %></p>
  </div>
  <% end %><br>

</div>